name: demo_modul4
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  dio: ^5.3.3
  logger: ^2.0.2
  geolocator: ^12.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  get_storage: ^2.1.1
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
